version: "3.8"

services:

  backend:
    container_name: backend # Nombre del contenedor
    build: . # Ubicación del archivo Dockerfile
    ports: 
      - "8080:8080"
    networks: 
      - appCorralon
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/corralon?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: nico
      SPRING_DATASOURCE_PASSWORD: 123
   # depends_on: # "backend" inicia despues que se termine de cargar el servicio "db"
    #  - db

  # Servicio 'db', contiene las configuraciones para la base de datos


networks: # Configuración de la red de docker
  appCorralon:
    driver: bridge
